Repository skku-amang/main, pull requests merged in 2024-08, with the labels that each got.

#7 chore: add favicon and set metadata
  public/next.svg
  public/vercel.svg
  src/app/(home)/layout.tsx
  src/app/favicon.ico
Labels: 🎨 Html&css

#23 16 scaffold team detail page
  .eslintrc.json
  next.config.mjs
  package-lock.json
  package.json
  src/app/(etc)/layout.tsx
  src/app/(etc)/notices/page.tsx
  src/app/(etc)/performances/[id]/page.tsx
  src/app/(etc)/signup/page.tsx
  src/app/(etc)/teams/[id]/page.tsx
  src/app/(etc)/teams/page.tsx
  src/app/(home)/layout.tsx
  src/app/(home)/page.tsx
  src/components/TeamDetail/MemberSessionTable.tsx
  src/components/TeamDetail/PromotionPostList.tsx
  src/components/TeamDetail/SongInfo.tsx
  src/components/TeamDetail/TeamInfo.tsx
  src/components/TeamListTable/columns.tsx
  src/components/TeamListTable/data-table.tsx
  src/components/common/DescribeToJSX.tsx
  src/components/common/Footer.tsx
  src/components/common/Form/SimpleDateField.tsx
  src/components/common/Form/SimpleDescription.tsx
  src/components/common/Form/SimpleImageField.tsx
  src/components/common/Form/SimpleLabel.tsx
  src/components/common/Form/SimpleStringField.tsx
  src/components/common/Header.tsx
  src/components/common/HeightPopulatedBody.tsx
  src/components/common/ImageLoader.tsx
  src/components/common/NavLink.tsx
  src/components/performances/PerformanceCard.tsx
  src/components/performances/PerformanceCardList.tsx
  src/components/performances/PerformanceForm.tsx
  src/components/ui/avatar.tsx
  src/components/ui/badge.tsx
  src/components/ui/calendar.tsx
  src/components/ui/card.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/datetimePicker.tsx
  src/components/ui/dialog.tsx
  src/components/ui/form.tsx
  src/components/ui/label.tsx
  src/components/ui/popover.tsx
  src/components/ui/table.tsx
  src/lib/dummy/Notice.ts
  src/lib/dummy/Performance.ts
  src/lib/dummy/Session.ts
  src/lib/dummy/Team.ts
  src/lib/dummy/User.ts
  src/lib/dummy/index.ts
  src/lib/youtube/Player.tsx
  src/lib/youtube/index.tsx
  tailwind.config.ts
  types/Performance.ts
  types/Session.ts
  types/Team.ts
Labels: ✨ Feature, 🪜 Scaffold

#31 17 user list
  app/(etc)/gallery/page.tsx
  app/(etc)/members/[id]/edit/page.tsx
  app/(etc)/members/[id]/page.tsx
  app/(etc)/members/page.tsx
  app/(etc)/signup/page.tsx
  components/MemberListTable/columns.tsx
  components/MemberListTable/data-table.tsx
  components/common/Header/index.tsx
  constants/routes.ts
  lib/dummy/Session.ts
  lib/dummy/User.ts
  package-lock.json
  tsconfig.json
  types/User.ts
Labels: ✨ Feature
