Repository skku-amang/main, pull requests merged in 2024-09, with the labels that each got.

#38 네비게이션 바 반응형 디자인 추가 했습니다.
  app/login/layout.tsx
  components/common/Header/index.tsx
  components/common/NavLink.tsx
Labels: 💻 반응형

#44 feat: implement new style
  tokens.json
Labels: ⚙ Setting, 🎨 Html&css

#46 23 filter and list padding
  app/(home)/page.tsx
  components/MemberListTable/data-table.tsx
  components/TeamListTable/data-table.tsx
  components/common/Filter.tsx
  components/ui/table.tsx
  lib/dummy/Session.ts
Labels: 🔨 리팩토링
