Repository skku-amang/main, pull requests merged in 2025-09, with the labels that each got.

#196 feat(api): Implement Team-related Prisma model with api (CRUD, apply, unapply)
  apps/api/src/app.module.ts
  apps/api/src/auth/guards/team-owner.guard.ts
  apps/api/src/team/dto/create-team.dto.ts
  apps/api/src/team/dto/team-application.dto.ts
  apps/api/src/team/dto/update-team.dto.ts
  apps/api/src/team/team.controller.spec.ts
  apps/api/src/team/team.controller.ts
  apps/api/src/team/team.module.ts
  apps/api/src/team/team.service.spec.ts
  apps/api/src/team/team.service.ts
  packages/api-client/src/errors.ts
  packages/api-client/src/index.ts
  packages/database/prisma/migrations/20250826062353_implement_team_model/migration.sql
  packages/database/prisma/schema.prisma
  packages/shared-types/src/index.ts
  packages/shared-types/src/team/create-team.schema.ts
  packages/shared-types/src/team/index.ts
  packages/shared-types/src/team/team-application.schema.ts
  packages/shared-types/src/team/update-team.schema.ts
Labels: 📬 API, Backend

#204 feat(ui): create week and month calendar components
  apps/web/app/(general)/(light)/reservations/_components/AddScheduleButton.tsx
  apps/web/app/(general)/(light)/reservations/_components/Calender/AddScheduleButton.tsx
  apps/web/app/(general)/(light)/reservations/_components/Calender/CalenderStyle.css
  apps/web/app/(general)/(light)/reservations/_components/Calender/fakePlan.ts
  apps/web/app/(general)/(light)/reservations/_components/Calender/index.tsx
  apps/web/app/(general)/(light)/reservations/_components/MobileCalendarField/MobileMonthBlock.tsx
  apps/web/app/(general)/(light)/reservations/_components/MobileCalendarField/index.tsx
  apps/web/app/(general)/(light)/reservations/_components/MonthCalendarField/MonthBlock.tsx
  apps/web/app/(general)/(light)/reservations/_components/MonthCalendarField/index.tsx
  apps/web/app/(general)/(light)/reservations/_components/MyReservationField/ReservationCard.tsx
  apps/web/app/(general)/(light)/reservations/_components/MyReservationField/index.tsx
  apps/web/app/(general)/(light)/reservations/_components/ReservationStatus/ReservationStatusCard.tsx
  apps/web/app/(general)/(light)/reservations/_components/ReservationStatus/index.tsx
  apps/web/app/(general)/(light)/reservations/_components/SmallCalendar.tsx
  apps/web/app/(general)/(light)/reservations/_components/WeekCalendarField/WeekColumn.tsx
  apps/web/app/(general)/(light)/reservations/_components/WeekCalendarField/index.tsx
  apps/web/app/(general)/(light)/reservations/_components/WeekLable.tsx
  apps/web/app/(general)/(light)/reservations/clubroom/page.tsx
  apps/web/app/(general)/(light)/reservations/equipment/page.tsx
  apps/web/components/ui/dropdown-menu.tsx
  apps/web/components/ui/tabs.tsx
  apps/web/package.json
  pnpm-lock.yaml
Labels: Frontend - Component

#217 feat: add web dev image
  .github/workflows/build-image.yml
  apps/web/Dockerfile.dev
Labels: Infra - CD
