Repository skku-amang/main, pull requests merged in 2025-07, with the labels that each got.

#158 Prisma Module Backend 도입
  apps/api/src/app.module.ts
  apps/api/src/prisma/prisma.module.ts
  apps/api/src/prisma/prisma.service.spec.ts
  apps/api/src/prisma/prisma.service.ts
  apps/api/tsconfig.json
Labels: ⚙ Setting, ✨ 기능, 🪜 스캐폴드

#160 User 모델 및 회원가입, 로그인(인증, 인가) 구현
  apps/api/package.json
  apps/api/src/app.module.ts
  apps/api/src/auth/auth.controller.spec.ts
  apps/api/src/auth/auth.controller.ts
  apps/api/src/auth/auth.module.ts
  apps/api/src/auth/auth.service.spec.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/auth/guards/access-token.guard.ts
  apps/api/src/auth/guards/refresh-token.guard.ts
  apps/api/src/auth/strategies/access-token.strategy.ts
  apps/api/src/auth/strategies/refresh-token.strategy.ts
  apps/api/src/main.ts
  apps/api/src/prisma/prisma.service.ts
  apps/api/src/users/users.module.ts
  apps/api/src/users/users.service.spec.ts
  apps/api/src/users/users.service.ts
  apps/api/tsconfig.json
  packages/database/index.ts
  packages/database/package.json
  packages/database/prisma/migrations/20250706162100_init_user_model/migration.sql
  packages/database/prisma/migrations/migration_lock.toml
  packages/database/prisma/schema.prisma
  packages/database/src/index.ts
  packages/shared-types/package.json
  packages/shared-types/src/constants/regex.ts
  packages/shared-types/src/index.ts
  packages/shared-types/src/user/create-user.dto.ts
  packages/shared-types/src/user/login-user.dto.ts
  packages/shared-types/tsconfig.json
  packages/shared-types/tsup.config.ts
  packages/typescript-config/base.json
  packages/typescript-config/package.json
  pnpm-lock.yaml
Labels: ✨ 기능, 📬 API

#169 Feature implement kubernetes
  .dockerignore
  .github/workflows/build-image.yml
  .github/workflows/ci.yml
  apps/api/Dockerfile
  apps/web/.dockerignore
  apps/web/Dockerfile
  apps/web/package.json
  helm/api/Chart.yaml
  helm/api/templates/configmap.yaml
  helm/api/templates/deployment.yaml
  helm/api/templates/ingress.yaml
  helm/api/templates/service.yaml
  helm/api/values-prod.yaml
  helm/api/values-staging.yaml
  helm/api/values.yaml
  helm/web/Chart.yaml
  helm/web/templates/configmap.yaml
  helm/web/templates/deployment.yaml
  helm/web/templates/ingress.yaml
  helm/web/templates/service.yaml
  helm/web/values-prod.yaml
  helm/web/values-staging.yaml
  helm/web/values.yaml
  pnpm-lock.yaml
Labels: Infra

#171 SearchBar 컴포넌트 제작
  apps/web/app/test/_components/SearchBar.tsx
  apps/web/app/test/page.tsx
Labels: 🎨 Html&css, Frontend

#179 Convert class-validator into zod
  apps/api/package.json
  apps/api/src/generation/generation.controller.ts
  apps/api/src/main.ts
  packages/shared-types/package.json
  packages/shared-types/src/constants/regex.ts
  packages/shared-types/src/decorators/is-in-half-steps.decorator.ts
  packages/shared-types/src/generation/create-generation.dto.ts
  packages/shared-types/src/generation/create-generation.schema.ts
  packages/shared-types/src/generation/update-generation.dto.ts
  packages/shared-types/src/generation/update-generation.schema.ts
  packages/shared-types/src/index.ts
  packages/shared-types/src/user/create-user.dto.ts
  packages/shared-types/src/user/create-user.schema.ts
  packages/shared-types/src/user/login-user.dto.ts
  packages/shared-types/src/user/login-user.schema.ts
  pnpm-lock.yaml
Labels: 🔨 리팩토링, Backend
